# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BeaconUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PiBeacon(object):
    def setupUi(self, PiBeacon):
        PiBeacon.setObjectName(_fromUtf8("PiBeacon"))
        PiBeacon.resize(608, 405)
        PiBeacon.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(PiBeacon)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setTabPosition(QtGui.QTabWidget.North)
        self.tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabs.setUsesScrollButtons(False)
        self.tabs.setDocumentMode(True)
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.bcscan = QtGui.QGroupBox(self.tab_5)
        self.bcscan.setTitle(_fromUtf8(""))
        self.bcscan.setObjectName(_fromUtf8("bcscan"))
        self.gridLayout = QtGui.QGridLayout(self.bcscan)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableView = QtGui.QTableView(self.bcscan)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout.addWidget(self.tableView, 0, 1, 1, 1)
        self.bcscanstop = QtGui.QPushButton(self.bcscan)
        self.bcscanstop.setMinimumSize(QtCore.QSize(0, 40))
        self.bcscanstop.setObjectName(_fromUtf8("bcscanstop"))
        self.gridLayout.addWidget(self.bcscanstop, 3, 0, 1, 1)
        self.bcscanstart = QtGui.QPushButton(self.bcscan)
        self.bcscanstart.setMinimumSize(QtCore.QSize(0, 40))
        self.bcscanstart.setObjectName(_fromUtf8("bcscanstart"))
        self.gridLayout.addWidget(self.bcscanstart, 3, 1, 1, 1)
        self.bcscanausgabe = QtGui.QTextBrowser(self.bcscan)
        self.bcscanausgabe.setObjectName(_fromUtf8("bcscanausgabe"))
        self.gridLayout.addWidget(self.bcscanausgabe, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.bcscan)
        self.tabs.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.createTbBtn = QtGui.QPushButton(self.groupBox)
        self.createTbBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.createTbBtn.setObjectName(_fromUtf8("createTbBtn"))
        self.verticalLayout_3.addWidget(self.createTbBtn)
        self.insertTbBtn = QtGui.QPushButton(self.groupBox)
        self.insertTbBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.insertTbBtn.setObjectName(_fromUtf8("insertTbBtn"))
        self.verticalLayout_3.addWidget(self.insertTbBtn)
        self.queryTbBtn = QtGui.QPushButton(self.groupBox)
        self.queryTbBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.queryTbBtn.setObjectName(_fromUtf8("queryTbBtn"))
        self.verticalLayout_3.addWidget(self.queryTbBtn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.getSysBtn = QtGui.QPushButton(self.tab)
        self.getSysBtn.setObjectName(_fromUtf8("getSysBtn"))
        self.gridLayout_2.addWidget(self.getSysBtn, 1, 0, 1, 1)
        self.stopGetSysBtn = QtGui.QPushButton(self.tab)
        self.stopGetSysBtn.setObjectName(_fromUtf8("stopGetSysBtn"))
        self.gridLayout_2.addWidget(self.stopGetSysBtn, 1, 1, 1, 1)
        self.sysInfoLbl = QtGui.QLabel(self.tab)
        self.sysInfoLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sysInfoLbl.setWordWrap(True)
        self.sysInfoLbl.setObjectName(_fromUtf8("sysInfoLbl"))
        self.gridLayout_2.addWidget(self.sysInfoLbl, 2, 0, 1, 2)
        self.tabs.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setStyleSheet(_fromUtf8("QPushButton { background-color: white; border: none; }\\n"))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(33, 255, 6); border: none; }\n"
""))
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet(_fromUtf8("QPushButton { background-color: white; border: none; }"))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(_fromUtf8("QPushButton { background-color: yellow; border: none; }\n"
""))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet(_fromUtf8("QPushButton { background-color: white; border: none; }"))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.gridLayout_3.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(_fromUtf8("QPushButton { background-color: blue; border: none; }\n"
""))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet(_fromUtf8("QPushButton { background-color: white; border: none; }"))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet(_fromUtf8("QPushButton { background-color: lightgray; border: none; }\n"
""))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet(_fromUtf8("QPushButton { background-color: white; border: none; }"))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.gridLayout_3.addWidget(self.groupBox_8, 1, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.led1Lbl = QtGui.QLabel(self.groupBox_9)
        self.led1Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.led1Lbl.setObjectName(_fromUtf8("led1Lbl"))
        self.horizontalLayout_8.addWidget(self.led1Lbl)
        self.led2Lbl = QtGui.QLabel(self.groupBox_9)
        self.led2Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.led2Lbl.setObjectName(_fromUtf8("led2Lbl"))
        self.horizontalLayout_8.addWidget(self.led2Lbl)
        self.statuLabel = QtGui.QLabel(self.groupBox_9)
        self.statuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statuLabel.setObjectName(_fromUtf8("statuLabel"))
        self.horizontalLayout_8.addWidget(self.statuLabel)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.becon_info_label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.becon_info_label.sizePolicy().hasHeightForWidth())
        self.becon_info_label.setSizePolicy(sizePolicy)
        self.becon_info_label.setMinimumSize(QtCore.QSize(0, 40))
        self.becon_info_label.setObjectName(_fromUtf8("becon_info_label"))
        self.gridLayout_4.addWidget(self.becon_info_label, 0, 0, 1, 2)
        self.statuLeftBtn = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statuLeftBtn.sizePolicy().hasHeightForWidth())
        self.statuLeftBtn.setSizePolicy(sizePolicy)
        self.statuLeftBtn.setAutoFillBackground(False)
        self.statuLeftBtn.setStyleSheet(_fromUtf8("QPushButton { background-color: blue; color: white;border: none; }\n"
""))
        self.statuLeftBtn.setAutoDefault(False)
        self.statuLeftBtn.setDefault(False)
        self.statuLeftBtn.setFlat(True)
        self.statuLeftBtn.setObjectName(_fromUtf8("statuLeftBtn"))
        self.gridLayout_4.addWidget(self.statuLeftBtn, 1, 0, 1, 1)
        self.statuRightBtn = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statuRightBtn.sizePolicy().hasHeightForWidth())
        self.statuRightBtn.setSizePolicy(sizePolicy)
        self.statuRightBtn.setAutoFillBackground(False)
        self.statuRightBtn.setStyleSheet(_fromUtf8("QPushButton { background-color: white; border: none; }"))
        self.statuRightBtn.setFlat(True)
        self.statuRightBtn.setObjectName(_fromUtf8("statuRightBtn"))
        self.gridLayout_4.addWidget(self.statuRightBtn, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.tabs.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabs)
        PiBeacon.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PiBeacon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        PiBeacon.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PiBeacon)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PiBeacon.setStatusBar(self.statusbar)
        self.actionSave_as = QtGui.QAction(PiBeacon)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.menuSave.addAction(self.actionSave_as)
        self.menubar.addAction(self.menuSave.menuAction())

        self.retranslateUi(PiBeacon)
        self.tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(PiBeacon)

    def retranslateUi(self, PiBeacon):
        PiBeacon.setWindowTitle(_translate("PiBeacon", "PiBeacon", None))
        self.bcscanstop.setText(_translate("PiBeacon", "Stop", None))
        self.bcscanstart.setText(_translate("PiBeacon", "Scannen", None))
        self.bcscanausgabe.setHtml(_translate("PiBeacon", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _translate("PiBeacon", "Beacon Scan", None))
        self.createTbBtn.setText(_translate("PiBeacon", "新建表", None))
        self.insertTbBtn.setText(_translate("PiBeacon", "查询数据", None))
        self.queryTbBtn.setText(_translate("PiBeacon", "插入数据", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("PiBeacon", "Sqlite", None))
        self.getSysBtn.setText(_translate("PiBeacon", "get System Info", None))
        self.stopGetSysBtn.setText(_translate("PiBeacon", "stop get SystemInfo", None))
        self.sysInfoLbl.setText(_translate("PiBeacon", "TextLabel", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("PiBeacon", "System", None))
        self.pushButton_3.setText(_translate("PiBeacon", "IS READY", None))
        self.pushButton_7.setText(_translate("PiBeacon", "Please Come In", None))
        self.pushButton.setText(_translate("PiBeacon", "IN USE", None))
        self.pushButton_9.setText(_translate("PiBeacon", "Now Serve", None))
        self.pushButton_2.setText(_translate("PiBeacon", "IN SERVICE", None))
        self.pushButton_8.setText(_translate("PiBeacon", "Now Serve", None))
        self.pushButton_4.setText(_translate("PiBeacon", "NEED CLEAN", None))
        self.pushButton_10.setText(_translate("PiBeacon", "Do not enter", None))
        self.led1Lbl.setText(_translate("PiBeacon", "Led1Label", None))
        self.led2Lbl.setText(_translate("PiBeacon", "Led2Label", None))
        self.statuLabel.setText(_translate("PiBeacon", "StatuLabel", None))
        self.groupBox_4.setTitle(_translate("PiBeacon", "CURRENT:", None))
        self.becon_info_label.setText(_translate("PiBeacon", "TextLabel", None))
        self.statuLeftBtn.setText(_translate("PiBeacon", "IN SERVICE", None))
        self.statuRightBtn.setText(_translate("PiBeacon", "NOW SERVE", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("PiBeacon", "页", None))
        self.menuSave.setTitle(_translate("PiBeacon", "Save", None))
        self.actionSave_as.setText(_translate("PiBeacon", "Save values", None))

import gui.qtres
